-- Analytical function in Windows functions
SELECT marks,
FIRST_VALUE (marks) OVER (ORDER BY marks) AS "FIRST_NAME",
LAST_VALUE (marks) OVER (ORDER BY marks) AS "LAST_NAME",
LEAD(marks) OVER (ORDER BY marks) AS "LEAD",
LAG(marks) OVER (ORDER BY marks) AS "LAG"
FROM student;

-- Analytical functions in Windows functions
SELECT marks,
FIRST_VALUE(marks) OVER(ORDER BY marks) AS "FIRST_NAME",
LAST_VALUE(marks) OVER(ORDER BY marks) AS "LAST_NAME",
LEAD(marks) OVER(ORDER BY marks) AS "LEAD",
LAG(marks) OVER(ORDER BY marks) AS "LAG"
FROM student;

SELECT marks,
FIRST_VALUE(marks) OVER(ORDER BY marks ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING)  AS "FIRST_NAME",
LAST_VALUE(marks) OVER(ORDER BY marks ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS "LAST_NAME",
LEAD(marks) OVER(ORDER BY marks ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS "LEAD",
LAG(marks) OVER(ORDER BY marks ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS "LAG"
FROM student;