SELECT CURRENT_TIMESTAMP;
SELECT MINUTE(CURRENT_TIMESTAMP);
SELECT SECOND(CURRENT_TIMESTAMP);
SELECT HOUR(CURRENT_TIMESTAMP);
SELECT MONTH(CURRENT_TIMESTAMP);
SELECT DAY(CURRENT_TIMESTAMP);
SELECT QUARTER(CURRENT_TIMESTAMP);
SELECT DAYOFWEEK(CURRENT_TIMESTAMP);


-- DATEDIFF    This is used to find the difference between the dates-- Always Remember that date1 > date2
SELECT DATEDIFF('2023-06-05','2023-06-01') AS Difference;

-- TIMEDIFF -- This is used to find the difference between the dates

SELECT TIMEDIFF(' 2023-07-06 12:30:00','2023-07-05 11:30:00') AS Difference;

-- 
SELECT * FROM accounts;

-- DATEFORMAT()
SELECT DATE_FORMAT('2023-01-20 10:30:02','%h:%i %p') AS formatted_time;


