SELECT marks,
ROW_NUMBER() OVER(ORDER BY marks) AS "ROW NUMBER",
RANK() OVER(ORDER BY marks) AS "RANK",
DENSE_RANK() OVER(ORDER BY marks) AS "DENSE_RANK",
PERCENT_RANK() OVER(ORDER BY marks) AS "PER_RANK"
FROM student;


-- RANKING FUNCTIONS IN WINDOWS FUNCTIONS
SELECT marks,
ROW_NUMBER() OVER(ORDER BY marks) AS "ROW_NUMBER",
RANK() OVER(ORDER BY marks) AS "RANK",
DENSE_RANK() OVER(ORDER BY marks) AS "DENSE_RANK",
PERCENT_RANK() OVER(ORDER BY marks) AS "PER_RANK"
FROM student;




SELECT marks,
ROW_NUMBER() OVER(ORDER BY marks ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS "ROW_NUMBER",
RANK() OVER(ORDER BY marks ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS "RANK",
DENSE_RANK() OVER(ORDER BY marks ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS "DENSE_RANK",
PERCENT_RANK() OVER(ORDER BY marks ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS "PER_RANK"
FROM student;